{% set version = "3.0.6" %}

package:
  name: erd
  version: {{ version }}

source:
  git_url: git@github.com:psi4/erd.git                 # [linux]
  git_url: https://github.com/psi4/erd.git             # [osx]
  git_tag: v{{ version }}

build:
  number: 0
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.0
    - gcc              # [osx]    # build w/conda gfortran
    - gcc-5-mp         # [linux]  # detect Fortran/C module mangling
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath, libgcc_s

test:
  commands:
    # Verify library
    - test -f $PREFIX/lib/liberd$SHLIB_EXT
    # Inspect linkage
    - ldd -v $PREFIX/lib/liberd.so       # [linux]
    - otool -L $PREFIX/lib/liberd.dylib  # [osx]

about:
  home: https://github.com/psi4/erd
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "AcesIII electron repulsion integrals"
  readme: README.md

