# no idea what version
{% set version = "0.0.1" %}

package:
  name: erd
  version: {{ version }}

source:
  git_url: git@github.com:psi4/erd.git                 # [linux]
  git_url: https://github.com/psi4/erd.git             # [osx]
  #git_tag: v{{ version }}

build:
  number: 0
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.0
    - gcc              # [osx]    # build w/conda gfortran
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath, libgcc_s

test:
  commands:
    # Verify libraries and executable.
    - test -f $PREFIX/lib/liberd.so       # [linux]
    - test -f $PREFIX/lib/liberd.dylib    # [osx]

about:
  home: https://github.com/psi4/erd
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "AcesIII electron repulsion integrals"
  readme: README.md

