package:
  name: psi4-deps
  version: "1.0"

source:
  path: ../psi4-deps-src

build:
  skip: true                                           # [win]
  number: 0
  entry_points:
    - help-psi4-deps = help_psi4_deps:main_help

requirements:
  build:
    - python x.x                  # define site-packages install dir
  run:
    # non-qc
    - cmake >3.3
    - gcc-5-mp         # [linux]
    - gcc              # [osx]    # gfortran
    - numpy
    - python x.x
    # link-time qc
    - chemps2
    - libefp
    - erd
    - gdma
    - libint
    - pcmsolver
    # run-time qc
    - dftd3
    - gcp
#    - v2rdm_casscf
    # docs
    - pytest
    - docutils 0.12*
    - sphinx 1.5*

test:
  commands:
    # Verify existence and execution
    - test -f $PREFIX/share/cmake/psi4/psi4DepsCache.cmake
#    - $PREFIX/bin/psi4 --version
    # Actually test
    - conda list

about:
  home: http://www.psicode.org
  license: GNU General Public License v2 or later (GPLv2+)
  #license_file: LICENSE
  summary: "dependency and cache metapackage for Psi4: open-source quantum chemistry"
  #readme: README.md

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../../hrw-conda
#build/number: 1
#build/string: abc
