{% set version = "1.8" %}

package:
  name: pcmsolver
  version: {{ version }}

source:
  git_url: git@github.com:loriab/pcmsolver.git      # [linux]
  git_url: https://github.com/loriab/pcmsolver.git  # [osx]
  git_tag: config6
  #git_url: git@github.com:PCMSolver/pcmsolver.git      # [linux]
  #git_url: https://github.com/PCMSolver/pcmsolver.git  # [osx]
  #git_tag: v{{ version }}

build:
  number: 2
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.1
    - gcc              # [osx]    # build w/ gfortran
    - gcc-5-mp         # [linux]
    - python x.x                  # for site-packages location, install selection
    - zlib
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath
    - zlib                        # link libz
    - python x.x                  # interpreter

test:
  commands:
    # Verify library.
    - test -f $PREFIX/lib/libpcm.so      # [linux]
    - test -f $PREFIX/lib/libpcm.dylib   # [osx]
    - ldd -v $PREFIX/lib/libpcm.so       # [linux]
    - otool -L $PREFIX/lib/libpcm.dylib  # [osx]
    # Verify python module.
    - test -f $PREFIX/lib/python2.7/site-packages/pcmsolver/pcmsolver.py  # [py27]
    - test -f $PREFIX/lib/python3.5/site-packages/pcmsolver/pcmsolver.py  # [py35]

about:
  home: http://pcmsolver.readthedocs.org/en/latest/
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: "Polarizable Continuum Model API"
  readme: README.md

