{% set version = "1.1.10" %}

package:
  name: pcmsolver
  version: {{ version }}

source:
  git_url: git@github.com:PCMSolver/pcmsolver.git      # [linux]
  git_url: https://github.com/PCMSolver/pcmsolver.git  # [osx]
  git_tag: v{{ version }}
  #git_url: git@github.com:loriab/pcmsolver.git      # [linux]
  #git_tag: config8

build:
  number: 0
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.1
    - gcc              # [osx]    # build w/ gfortran
    - gcc-5-mp         # [linux]
    - python x.x                  # for site-packages location, install selection
    - zlib
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath
    - zlib                        # link libz
    - python x.x                  # interpreter

test:
  commands:
    # Verify library and python module
    - test -f $PREFIX/lib/libpcm$SHLIB_EXT
    - test -f $SP_DIR/pcmsolver/pcmsolver.py
    # Inspect linkage
    - ldd -v $PREFIX/lib/libpcm.so       # [linux]
    - otool -L $PREFIX/lib/libpcm.dylib  # [osx]
    - conda-inspect linkages pcmsolver --show-files

about:
  home: http://pcmsolver.readthedocs.org/en/latest/
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: "Polarizable Continuum Model API"
  readme: README.md

