{% set version = "2.2.6" %}

package:
    name: gdma
    version: {{ version }}

source:
    git_url: git@github.com:psi4/gdma.git                # [linux]
    git_url: https://github.com/psi4/gdma.git            # [osx]
    git_tag: v{{ version }}

build:
    number: 5                                            # [linux]
    number: 4                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    run_exports:
        - {{ pin_subpackage('gdma', max_pin='x.x.x') }}
    ignore_run_exports:
        # unused libraries
        - libgcc-ng
        - libgfortran-ng

requirements:
    build:
        - cmake >=3.0
        - {{ compiler('c') }}                            # [osx]
        - {{ compiler('fortran') }}
        - llvm-openmp                                    # [osx]
        - intel-openmp                                   # [osx]

test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libgdma$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libgdma.so    # [linux]
        - ldd -v $PREFIX/lib/libgdma.so       # [linux]
        - otool -L $PREFIX/lib/libgdma.dylib  # [osx]
        - conda-inspect linkages gdma --show-files

about:
    home: http://www-stone.ch.cam.ac.uk/programs.html
    dev_url: https://github.com/psi4/gdma
    doc_url: http://www-stone.ch.cam.ac.uk/pub/gdma/index.php
    # doc_source_url:
    license: GPL-2.0+
    license_url: https://opensource.org/licenses/GPL-2.0
    license_file: LICENSE
    license_family: GPL
    summary: "A. Stone's Gaussian distributed multipole analysis (GDMA)"
    # description: >
