{% set version = "2.2.6" %}

package:
  name: gdma
  version: {{ version }}

source:
  git_url: git@github.com:psi4/gdma.git                # [linux]
  git_url: https://github.com/psi4/gdma.git            # [osx]
  git_tag: v{{ version }}

build:
  number: 2                                            # [linux]
  number: 3                                            # [osx]
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.0
    - gcc              # [osx]    # build w/conda gfortran
    - gcc-5-mp         # [linux]  # detect Fortran/C module mangling
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath, libgcc_s

test:
  commands:
    # Verify library
    - test -f $PREFIX/lib/libgdma$SHLIB_EXT
    # Inspect linkage
    - ldd -r -u $PREFIX/lib/libgdma.so    # [linux]
    - ldd -v $PREFIX/lib/libgdma.so       # [linux]
    - otool -L $PREFIX/lib/libgdma.dylib  # [osx]
    - conda-inspect linkages gdma --show-files

about:
  home: https://github.com/psi4/gdma
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "A. Stone's Gaussian distributed multipole analysis (GDMA)"
  readme: README.md
