{% set version = "0.1.1" %}

package:
  name: ambit
  version: {{ version }}

source:
#  git_url: git@github.com:jturney/ambit.git            # [linux]
#  git_url: https://github.com/jturney/ambit.git        # [osx]
#  git_tag: v{{ version }}-alpha
  git_url: git@github.com:loriab/ambit.git             # [linux]
  git_url: https://github.com/loriab/ambit.git         # [osx]
  git_tag: boost61fix
#  path: ../../../ambit
#  path: ../../../nightly/ambit

build:
  number: 13
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - boost >=1.53                # works w/ 1.59 from channel menpo
    - cmake >=2.8.11
    - gcc              # [osx]    # build w/conda gcc
    - hdf5
    - python 2.7*
  run:
    - boost >=1.53
    - hdf5
    - libgcc           # [osx]    # link w/conda libstdc++, libgcc_s, libgomp
    - python 2.7*
    - zlib

test:
  commands:
    # Verify libraries and executable.
    - test -f $PREFIX/lib/libambit.a
    - test -f $PREFIX/lib/libambit.so     # [linux]
    - test -f $PREFIX/lib/libambit.dylib  # [osx]
    # Verify python module.
    - test -f ${PREFIX}/lib/python2.7/site-packages/ambit/pyambit.so
    # run_test executes lib/test_operators.py

about:
  home: https://github.com/jturney/ambit
  #license: GNU General Public License v2 or later (GPLv2+)
  summary: "C++ library for the implementation of tensor product calculations"
  readme: README.md

