{% set version = "1.0.1" %}


package:
  name: snsmp2
  version: {{ version }}

source:
  git_url: git@github.com:loriab/sns-mp2.git   # [linux]
  #git_url: git@github.com:DEShawResearch/sns-mp2.git   # [linux]
  #git_url: https://github.com/DEShawResearch/sns-mp2.git # [osx]
  #git_tag: {{ version }}
  #git_tag: 83281dc  # 1.0.1.dev10
  git_tag: importfixes

build:
  number: 0                                            # [linux]
  #number: 0                                            # [osx]
  skip: true                                           # [win]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python x.x
    - setuptools
    - pbr >=1.9
  run:
    - python x.x
    - scipy

test:
  #imports:
  #  - snsmp2
  commands:
    - conda-inspect linkages snsmp2 --show-files

about:
  home: https://github.com/DEShawResearch/sns-mp2
  license: BSD-2-Clause
  license_url: https://opensource.org/licenses/BSD-2-Clause
  license_file: LICENCE.txt
  summary: "R. McGibbon's spin-network-scaled MP2 plugin to Psi4"
  license_family: BSD

