{% set name = "openfermionpsi4" %}
{% set version = "0.3a1" %}  # TODO update

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    #git_url: git@github.com:quantumlib/OpenFermion-Psi4.git              # [linux]
    #git_url: https://github.com/quantumlib/OpenFermion-Psi4.git          # [osx]
    git_url: git@github.com:loriab/OpenFermion-Psi4.git              # [linux]
    git_url: https://github.com/loriab/OpenFermion-Psi4.git          # [osx]
    #git_tag: v{{ version }}
    #git_tag: v0.3
    git_tag:  loriab-patch-1

build:
    number: 0                                               # [linux]
    number: 0                                               # [osx]
    skip: true                                              # [win]
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python {{ python }}
        - setuptools
    run:
        - openfermion >=0.5
        - {{ pin_compatible('python', max_pin='x.x') }}

test:
#    requires:
#        - pytest
##        - psi4
    imports:
##        - psi4
        - openfermionpsi4
    commands:
        # Verify module
        - test -f $SP_DIR/openfermionpsi4/__init__.py
        # Inspect linkage
        - conda inspect linkages --show-files --groupby=dependency openfermionpsi4 openfermion
        - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
        # Actually test
##        - psi4 --test
##        - python -c "import resp, sys; sys.exit(resp.test())"
##        - python -c "import psi4, resp; print('*** resp {} built successfully against Psi4 {}. Buy psinet a beer.'.format(resp.__version__, psi4.__version__))"
#        #- pytest

about:
    home: https://www.openfermion.org
    dev_url: https://github.com/quantumlib/OpenFermion-Psi4
    # doc_url:
    # doc_source_url:
    license: LGPL-3.0
    license_url: https://opensource.org/licenses/LGPL-3.0
    license_file: LICENSE
    license_family: LGPL
    summary: "Google's plugin allowing OpenFermion to interface with Psi4"
    # description: >
