{% set version = "0.7a1" %}  # TODO get a tag when stable and bump and pull from tag below

package:
    name: v2rdm_casscf
    version: {{ version }}

source:
    #git_url: git@github.com:edeprince3/v2rdm_casscf.git      # [linux]
    git_url: git@github.com:loriab/v2rdm_casscf.git      # [linux]
    git_url: https://github.com/edeprince3/v2rdm_casscf.git  # [osx]
    #git_tag: v{{ version }}
    #git_tag: c12571d
    git_tag: verfix

build:
    number: 2                                            # [linux]
    number: 0                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    ignore_run_exports:
        # interferes with solving build env (at least for prereleases?)
        - psi4
        # unused libraries
        - libgfortran-ng

requirements:
    build:
        - cmake >=3.3
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
    host:
        - mkl-devel {{ mkl }}
        - psi4                                            # for psi4OptionsTools to initiate plugin and to link against
        - pybind11 {{ pybind11 }}
        - python {{ python }}                             # to resolve site-packages dir name
    run:
        - intel-openmp
        - {{ pin_compatible('python', max_pin='x.x') }}

test:
    requires:
        - psi4
    imports:
        - v2rdm_casscf
        - psi4
    commands:
        - export PLPSP=$PREFIX/lib{{ PYMOD_INSTALL_LIBDIR }}
        # Verify module
        - test -f $PLPSP/v2rdm_casscf/v2rdm_casscf.so
        - test -f $PREFIX/share/cmake/v2rdm_casscf/v2rdm_casscfConfig.cmake
        # Inspect linkage
        - ldd -r -u $PLPSP/v2rdm_casscf/v2rdm_casscf.so && return 0  # [linux]
        - ldd -v $PLPSP/v2rdm_casscf/v2rdm_casscf.so                 # [linux]
        - otool -L $PLPSP/v2rdm_casscf/v2rdm_casscf.so               # [osx]
        - conda-inspect linkages v2rdm_casscf --show-files
        # Actually test
        - psi4 --test
        # - psi4 $PLPSP/v2rdm_casscf/tests/v2rdm1/input.dat
        # - psi4 $PLPSP/v2rdm_casscf/tests/v2rdm3/input.dat

about:
    home: https://github.com/edeprince3/v2rdm_casscf
    dev_url: https://github.com/edeprince3/v2rdm_casscf
    doc_url: https://github.com/edeprince3/v2rdm_casscf/blob/master/README.md
    # doc_source_url:
    license: GPL-2.0+
    license_url: https://opensource.org/licenses/GPL-2.0+
    license_file: LICENSE
    license_family: GPL
    summary: "E. DePrince's variational 2-RDM-driven CASSCF plugin to Psi4"
    # description: >

# NOTES
# -----

# * To build against a certain, non-latest psi4, `req/host` will be e.g., `psi4 1.1+add49b9`
