{% set version = "1.2" %}

package:
  name: dkh
  version: {{ version }}

source:
  git_url: git@github.com:psi4/dkh.git                 # [linux]
  git_url: https://github.com/psi4/dkh.git             # [osx]
  git_tag: v{{ version }}

build:
  number: 0                                            # [linux]
  number: 1                                            # [osx]
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.0
    - gcc              # [osx]    # build w/conda gfortran
    - gcc-5-mp         # [linux]  # detect Fortran/C module mangling
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath, libgcc_s

test:
  commands:
    # Verify library
    - test -f $PREFIX/lib/libdkh$SHLIB_EXT
    # Inspect linkage
    - ldd -r -u $PREFIX/lib/libdkh.so && return 0  # [linux]
    - ldd -v $PREFIX/lib/libdkh.so                 # [linux]
    - otool -L $PREFIX/lib/libdkh.dylib            # [osx]
    - conda-inspect linkages dkh --show-files

about:
  home: https://github.com/psi4/dkh
  #license: BSD 2-clause
  summary: "Wolf, Reiher, and Hess's Douglas-Kroll-Hess (DKH) relativistic correction"
  readme: README.md

