package:
  name: psi4-dev
  version: 1.1rc2

source:
  path: ../psi4-dev-src

build:
  skip: true                                           # [win]
  number: 1

requirements:
  build:
    - python x.x                  # define site-packages install dir
  run:
    # non-qc
    - cmake >3.3
    - gcc-5-mp         # [linux]
    - gcc              # [osx]    # gfortran
#    - numpy
    - python x.x
    # link-time qc
    - psi4-lt-mp
    #- chemps2
    #- libefp
    #- erd
    #- gdma
    #- libint
    #- pcmsolver
    #- simint
    # run-time qc
#    - dftd3
#    - gcp
#    - v2rdm_casscf
    # docs
    - pytest
    - docutils 0.12*
    - sphinx 1.5*

test:
  commands:
    # Verify existence and execution
    - test -f $PREFIX/bin/psi4-path-advisor
    - test -f $PREFIX/share/cmake/psi4/psi4DepsCache.cmake
    # Actually test
    - conda list

about:
  home: http://psicode.org
  summary: development metapackage for Psi4 including CMake cache, documentation, & compiler tools
  #description:
