{% set version = "1.1" %}

package:
  name: psi4-dev
  version: {{ version }}

source:
  path: ../psi4-dev-src

build:
  skip: true           # [win]
  number: 0            # [osx]
  number: 1            # [linux]

requirements:
  build:
    - python x.x                  # define site-packages install dir
  run:
    # non-qc
    - cmake >3.3
    - gcc              # [osx]    # gfortran
    - gcc-5-mp         # [linux]
    - pytest
    - python x.x
    # qc
    - psi4-lt-mp {{ version }}
    # docs
    - docutils 0.12*
    - sphinx 1.5*

test:
  commands:
    # Verify existence and execution
    - test -f $PREFIX/bin/psi4-path-advisor
    - test -f $PREFIX/share/cmake/psi4/psi4DepsCache.cmake
    # Actually test
    - conda list

about:
  home: http://psicode.org
  summary: development metapackage for Psi4 including CMake cache, documentation, & compiler tools
  #description:
