{% set version = "0.1" %}

package:
  name: v2rdm_casscf
  version: {{ version }}

source:
  git_url: git@github.com:edeprince3/v2rdm_casscf.git      # [linux]
  git_url: https://github.com/edeprince3/v2rdm_casscf.git  # [osx]
#  git_tag: v{{ version }}

build:
  number: 18
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - gcc              # [osx]    # build w/ gcc, gfortran
    - psi4                        # for headers (psi4 & boost)
    - python 2.7*                 # for install location at python2.7/site-packages
  run:
    - libgcc           # [osx]    # link libstdc++, libgcc_s
    - psi4

test:
  commands:
    # Verify plugin library.
    - test -f $PREFIX/lib/python2.7/site-packages/v2rdm_casscf/v2rdm_casscf.so
    # run_test executes tests/v2rdm1

about:
  home: https://github.com/edeprince3/v2rdm_casscf
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "a variational 2-RDM-driven CASSCF plugin to Psi4"
  readme: README.md

