{% set version = "0.1" %}

package:
  name: v2rdm_casscf
  version: {{ version }}

source:
  git_url: git@github.com:edeprince3/v2rdm_casscf.git      # [linux]
  git_url: https://github.com/edeprince3/v2rdm_casscf.git  # [osx]
  git_tag: v{{ version }}

build:
  number: 8
  binary_relocation: true

requirements:
  build:
    - python 2.7*                 # for site-packages location to install
    - psi4                        # for headers
    - boost            # [osx]    # for headers
    - gcc              # [osx]    # build w/conda gcc, gfortran & libstdc++
  run:
    - psi4
    - libgcc           # [osx]    # link against libstdc++, libgcc_s

test:
  commands:
    # Verify plugin library.
    - test -f $PREFIX/lib/python2.7/site-packages/v2rdm_casscf/v2rdm_casscf.so
    # run_test executes tests/v2rdm1

about:
  home: https://github.com/edeprince3/v2rdm_casscf
  #license: GNU General Public License v2 or later (GPLv2+)
  summary: "a variational 2-RDM-driven CASSCF plugin to Psi4"
  readme: README.md


# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../../nightly/v2rdm_casscf
#build/number: 1
#build/string: abc
