{% set version = "0.4" %}

{% set mklver = "2017.0.3" %}
{% set defisa = "avx2" %}
{% set isa = environ.get("PSI_BUILD_ISA", defisa) %}
{% set ccfam = environ.get("PSI_BUILD_CCFAM", "default") %}


package:
  name: v2rdm_casscf
  version: {{ version }}

source:
  git_url: git@github.com:edeprince3/v2rdm_casscf.git      # [linux]
  git_url: https://github.com/edeprince3/v2rdm_casscf.git  # [osx]
  #git_tag: v{{ version }}
  git_tag: 5f48d9

# build notes:
#   0.3: 1 works 1.1, 2 works w/libxc, 3 works w/general maint.
#        post_genmaint 0.3 build 3: git_url: https://github.com/loriab/v2rdm_casscf.git git_tag: 833b18f
#   0.4: 0 works w/general maint. (-- 0.3_3), 1 works w/str irrep

build:
  number: 1                                            # [linux]
  number: 0                                            # [osx]
  binary_relocation: true
  skip: true                                           # [win]
  script_env:
    - PSI_BUILD_ISA                                    # [osx]
    - PSI_BUILD_CCFAM                                  # [osx]
  features:
    {% if isa != defisa %}
    - {{ isa }}                                        # [osx]
    {% endif %}
    {% if ccfam == "gnu" %}
    - {{ ccfam }}                                      # [osx]
    {% endif %}

requirements:
  build:
    - cmake >=3.1
    - gcc              # [osx]    # build w/conda gfortran
    - gcc-5-mp         # [linux]
    - mkl {{ mklver }} # [osx]
    - psi4                        # for psi4OptionsTools to initiate plugin
    # for 1.1 pinned - psi4 1.1+add49b9                       # for psi4OptionsTools to initiate plugin
    - python x.x                  # for site-packages location
    {% if isa != defisa %}
    - {{ isa }}        # [osx]    # for oldmac selection
    {% endif %}
    {% if ccfam == "gnu" %}
    - gcc-5-mp         # [osx]
    {% endif %}
  run:
    #- gcc-5-mp        # [linux]  # link libgcc_s - not require at rt b/c to avoid interfering with other gcc
    {% if ccfam == "gnu" %}
    - gcc-5-mp         # [osx]    # link libstdc++
    {% else %}
    - libgcc           # [osx]    # link libgfortran, libquadmath, libgcc_s
    {% endif %}
    - mkl              # [linux]  # link libiomp5
    - mkl {{ mklver }} # [osx]
    #- psi4                       # load and support plugin
    - python x.x                  # interpreter
    {% if isa != defisa %}
    - {{ isa }}        # [osx]    # track oldmac
    {% endif %}
    {% if ccfam == "gnu" %}
    - {{ ccfam }}                                        # [osx]
    {% endif %}

test:
  commands:
    # Verify plugin module.
    - test -f $SP_DIR/v2rdm_casscf/v2rdm_casscf.so
    # Inspect linkage
    - ldd -r -u $SP_DIR/v2rdm_casscf/v2rdm_casscf.so && return 0  # [linux]
    - ldd -v $SP_DIR/v2rdm_casscf/v2rdm_casscf.so                 # [linux]
    - otool -L $SP_DIR/v2rdm_casscf/v2rdm_casscf.so               # [osx]
    - conda-inspect linkages v2rdm_casscf --show-files

about:
  home: https://github.com/edeprince3/v2rdm_casscf
  dev_url: https://github.com/edeprince3/v2rdm_casscf
  doc_url: https://github.com/edeprince3/v2rdm_casscf/blob/master/README.md
  license: GPL-2.0+
  license_url: https://opensource.org/licenses/GPL-2.0+
  license_file: LICENSE
  license_family: GPL2
  summary: E. DePrince's variational 2-RDM-driven CASSCF plugin to Psi4
  #description:
