# <<<  Compiler Stuff  >>>

c_compiler:
    - clang                            # [osx]
    - gcc                              # [linux]
cxx_compiler:
    - clangxx                          # [osx]
    - gxx                              # [linux]
fortran_compiler:
    - gfortran
target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]

# <<<  Packages Stuff  >>>

blas_impl:
    - mkl
    # - openblas  # not playing nicely with threading in psi4 at last check (May 2018)
hdf5:
    - 1.10.1  # this recipe pins to x.x.x which I trust more than the 1.8 recipe x.x
mkl:
    - 2018
openblas:
    - 0.2.20
pybind11:
    - 2.2.3
python:
    - 3.6
    - 2.7
    - 3.5
zlib:
    - 1.2

# <<<  Psi Stuff  >>>

ltrtver:
    # bump whenever a dep version bumps. beyond the "|" aren't in ltrtver.
    # bump whenever a dep version bumps: pb11   chemps2  dftd3  dkh  libefp erd   g2g   gcp   gdma  gpu   libint pcm      resp  sim  sns    v2rdm libxc | pylibefp
    # - "1.2a1.dev6"  # (   Apr 2018)    2.2.3  1.8.7b1  3.2.0  1.2  1.5b2        1.0.1 2.0.2 2.2.6       1.2.1  1.2.0rc1            1.0.1  0.7a1 4.0.1
    # - "1.2a1.dev7"  # ( 1 May 2018)    ...    1.8.7    ...    ...  ...          ...   ...   ...         ...    1.2.0rc2            ...    ...   ...
    # - "1.2a1.dev8"  # ( 1 May 2018)    ...    ...      ...    ...  ...          ...   ...   ...         ...    1.2.1               ...    ...   4.0.2
    # - "1.2a1.dev9"  # ( 6 May 2018)    ...    ...      ...    ...  1.5.0        ...   ...   ...         ...    ...                 ...    ...   ...   | 0.3
    # - "1.2a1.dev10" # (17 May 2018) psi4-dev/src changed - LAPACK_LIBRARIES
    # - "1.2a1.dev11" # ( 8 Jun 2018)    ...    ...      ...    ...  ...          1.1.0 ...   ...         ...    ...            0.7  ...    0.7a2 ...   | ...
    # - "1.2a2.dev12" # (12 Jun 2018)    ...    ...      ...    ...  ...          ...   ...   ...         ...    ...      0.7a3 ...  ...    0.7   ...   | ...
    - "1.2a2.dev13"   # (17 Jun 2018)    ...    ...      ...    ...  ...          ...   ...   ...   0.2   ...    ...      0.7   ...  ...    ...   ...   | ...
MAX_AM_ERI:
    - '6'
OPTS:
    - '-msse2 -axCORE-AVX2,AVX -Wl,--as-needed -static-intel -wd10237'  # [linux]
PY_ABBR:
    - python3.6m
    - python2.7
    - python3.5m
PYMOD_INSTALL_LIBDIR:
    - '/python3.6/site-packages'
    - '/python2.7/site-packages'
    - '/python3.5/site-packages'
chemps2:
    - 1.8.7
dftd3:
    - 3.2.0
dkh:
    - 1.2
libefp:
    - 1.5.0
erd:
    - 3.0.6
gau2grid:
    - 1.1.0
gcp:
    - 2.0.2
gdma:
    - 2.2.6
gpu_dfcc:
    - 0.2
libint:
    - 1.2.1
pcmsolver:
    - 1.2.1
pylibefp:
    - 0.3
resp:
    - 0.7
simint:
    - 0.7
snsmp2:
    - 1.0.1
v2rdm_casscf:
    - 0.7
libxc:
    - 4.0.2

# <<<  Concluding Stuff  >>>

zip_keys:
    - python
    - PYMOD_INSTALL_LIBDIR
    - PY_ABBR

# NOTES
# -----

# Ok pre-rel tags: 1.2.0rc1, 1.5b2

# * below bad b/c messed with predicted vs actual hashes, so didn't upload
#   ignore_version:
#       - PYMOD_INSTALL_LIBDIR
#       - PY_ABBR
