{% set gittag = GIT_DESCRIBE_TAG %}
{% set gitmicro = GIT_DESCRIBE_NUMBER|string %}
{% set buildno = "py%s_%s" % (PY_VER.replace('.', ''), GIT_DESCRIBE_HASH) %}

{% if gittag.endswith('rc') %}
    {% set version = "%s%s" % (gittag, gitmicro) %}
{% else %}
    {% set version = "%s.%s" % (gittag, gitmicro) %}
{% endif %}

package:
  name: psi4
  version: {{ version }}

source:
  git_url: git@github.com:psi4/psi4.git                # [linux]
  git_url: https://github.com/psi4/psi4.git            # [osx]
  git_tag: master

build:
  skip: true                                           # [win]
  string: {{ buildno }}
  binary_relocation: true
  binary_has_prefix_files:
    - bin/psi4
    - lib/python2.7/site-packages/psi4.so
  has_prefix_files:
    - bin/psi4-config
    - share/psi4/scripts/setenv.py
    - share/psi4/plugin/Makefile.template
    - share/psi4/python/pcm_placeholder.py

requirements:
  build:
    - psi4metapackage  # [linux]  # python 2.7*, boost, chemps2, pcmsolver, hdf5, gsl, zlib
    - boost 1.57.0 0   # [linux]  # boost *really* wants to be the latest build (1.57.0-4); though the right one's in the package this is an extra bit of persuasion
    - ambit            # [osx]
    - boost >=1.57     # [osx]
    - cmake >3         # [osx]
#    - dftd3m           # [linux]
    - gcc              # [osx]    # build w/conda gcc, gfortran
    - hdf5             # [osx]
    - libgcc           # [linux]
    - numpy            # [osx]    # psi4 execution w/i ctest and sphinxman #linux  # for psi4 execution w/i docs build
    - pcmsolver        # [osx]
    - pychemps2        # [osx]
    - python 2.7*      # [osx]
    - sphinx 1.3*      # [linux]  # for docs
    - zlib             # [osx]
  run:
#    - gsl              # [linux]
    - ambit            # [osx]
    - hdf5 1.8.16      # [linux]  # runtime hdf5 must match compiled-against hdf5 for chemps2
    - libgcc           # [osx]
    - ncurses          # [osx]
    - numpy            # [osx]
    - pcmsolver        # [linux]  # lib baked in but pkg needed for py module
    - pcmsolver        # [osx]
    - pychemps2        # [osx]
    - python 2.7*      # [osx]
    #- chemps2  # revive for download count?
#    - dftd3m           # [linux]
#    - v2rdm_casscf

test:
  commands:
    # Verify executable.
    - test -f $PREFIX/bin/psi4
    # Verify python module.
    - test -f $PREFIX/lib/python2.7/site-packages/psi4.so
    #- $PREFIX/bin/psi4 --help  # no good; exits 1 even upon success

about:
  home: http://www.psicode.org
  license: GNU General Public License v2 or later (GPLv2+)
  #license_file: LICENSE
  summary: "open-source quantum chemistry"
  #readme: README.md

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../../psi4mangle/psi4
#build/number: 1
#build/string: abc
