
{% set data = load_setup_py_data(setup_file='_conda_vers.py') %}

package:
  name: psi4
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/psi4/psi4.git
  git_tag: master
#  git_url: git@github.com:psi4/psi4.git                # [linux]
#  git_url: https://github.com/psi4/psi4.git            # [osx]

build:
  skip: true                                           # [win]
  number: 0
  binary_relocation: true
#  binary_has_prefix_files:
#    - bin/psi4
#    - lib/python2.7/site-packages/psi4.so
#  has_prefix_files:
#    - bin/psi4-config
#    - share/psi4/scripts/setenv.py
#    - share/psi4/plugin/Makefile.template
#    - share/psi4/python/pcm_placeholder.py

requirements:
  build:
    - cmake >3.1       # [osx]
    - dftd3            # [osx]  # for testing
    - libefp           # [osx]
    - gcc             # [osx]  # after working for gfortran
#    - gcc-5 5.3.0       # [osx]
    - gdma             # [osx]
    - libint           # [osx]
    - numpy            # [osx]  # for psi4 execution w/i ctest and sphinxman
    - python 2.7*      # [osx]
    - cmake >3.1       # [linux]
    - dftd3            # [linux]  # for testing
    - libefp           # [linux]
    - gcc-5            # [linux]
    - gdma             # [linux]
    - libint           # [linux]
    - numpy            # [linux]  # for psi4 execution w/i ctest and sphinxman
    - python x.x       # [linux]
    - sphinx 1.4*      # [linux]  # for docs
  run:
    - libefp           # [osx]  # link libefp
#    - gcc-5            # [osx]  # link libgcc_s
    - libgcc           # [osx]  # after working for libgfortran
    - gdma             # [osx]  # link libgdma
    - libint           # [osx]  # link libderiv, libint
#    - mkl              # [osx]  # link libiomp5
    - numpy            # [osx]
    - python 2.7*      # [osx]  # link libpython2.7
    - libefp           # [linux]  # link libefp
    - gcc-5            # [linux]  # link libgcc_s
    - gdma             # [linux]  # link libgdma
    - libint           # [linux]  # link libderiv, libint
    - mkl              # [linux]  # link libiomp5
    - numpy            # [linux]
    - python x.x       # [linux]  # link libpython

#    #- ambit 0.2       # [osx]
#    #- boost >=1.57    # [osx]
#    - cmake >3.1
#    - dftd3                       # for testing
#    - gcc              # [osx]    # build w/ gcc, gfortran
##    - libgcc           # [linux]
#    - gcc-5
#    - numpy                       # for psi4 execution w/i ctest and sphinxman
##    - pcmsolver >=1.1.2
##    - pychemps2 >=1.7.1
#    - python 2.7*
#    - sphinx 1.4*      # [linux]  # for docs
##    - zlib
#    - libint
#    - gdma
#    - libefp
#  run:
#    #- ambit 0.2       # [osx]    # link libambit
#    # hdf5                        # link libhdf5, libhdf5_hl (implicit w/ libchemp2)
#    - libgcc           # [osx]    # link libgfortran, libquadmath, libstdc++, libgcc_s, libgomp
##    - libgcc           # [linux]  # link libgcc_s
#    - gcc-5
##    - ncurses                     # for psi4 interactive
#    - mkl                         # link libiomp5 (psi4.so)
#    - numpy
##    - pcmsolver >=1.1.2           # link libpcm
##    - pychemps2 >=1.7.1           # link libchemps2
#    - python 2.7*                 # link libpython2.7
##    - zlib                        # link libz

test:
  commands:
    # Verify executable.
    - test -f $PREFIX/bin/psi4
    # Verify python module.
    - test -f $PREFIX/lib/python2.7/site-packages/psi4/core.so  # [py27]
    - test -f $PREFIX/lib/python3.5/site-packages/psi4/core.so  # [py35]
    # Verify execution.
    - $PREFIX/bin/psi4 --version

about:
  home: http://www.psicode.org
  license: GNU General Public License v2 or later (GPLv2+)
  #license_file: LICENSE
  summary: "open-source quantum chemistry"
  #readme: README.md

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../../psi4mangle/psi4
#build/number: 1
#build/string: abc
