package:
  name: psi4
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') + '.' + environ.get('GIT_DESCRIBE_NUMBER', 0)|string }}

source:
  git_url: git@github.com:psi4/psi4.git

build:
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_DESCRIBE_HASH', 'GIT_STUB') }}
  binary_relocation: true
  binary_has_prefix_files:
    - bin/psi4
  has_prefix_files:
    - share/psi4/scripts/setenv.py
    - share/psi4/python/pcm_placeholder.py
    - bin/psi4-config

requirements:
  build:
    - cmake >3                               [linux]
    - psi4metapackage  # python 2.7*, boost, chemps2, pcmsolver, hdf5, gsl, zlib
    - boost 1.57.0 0  # boost *really* wants to be the latest build (1.57.0-4); though the right one's in the package this is an extra bit of persuasion
    - libgcc
    - sphinx  # for docs
  run:
    - python 2.7*
    - gsl
    - hdf5
    - pcmsolver  # lib baked in but pkg needed for py module
    - ncurses
    #- chemps2  # revive for download count?

about:
  home: http://www.psicode.org
  license: GNU General Public License v2 or later (GPLv2+)
  #license_file: LICENSE
  summary: "open-source quantum chemistry"
  #readme: README.md

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../../psi4mangle/psi4
#build/number: 1
#build/string: abc
