{% set gittag = GIT_DESCRIBE_TAG %}
{% set gitmicro = GIT_DESCRIBE_NUMBER|string %}
{% set buildno = "py%s_%s" % (PY_VER.replace('.', ''), GIT_DESCRIBE_HASH) %}

{% if gittag.endswith('rc') %}
    {% set version = "%s%s" % (gittag, gitmicro) %}
{% else %}
    {% set version = "%s.%s" % (gittag, gitmicro) %}
{% endif %}

package:
  name: psi4
  version: {{ version }}

source:
  git_url: git@github.com:psi4/psi4.git                # [linux]
  git_url: https://github.com/psi4/psi4.git            # [osx]
  git_tag: master

build:
  skip: true                                           # [win]
  string: {{ buildno }}
  binary_relocation: true
  binary_has_prefix_files:
    - bin/psi4
    - lib/python2.7/site-packages/psi4.so
  has_prefix_files:
    - bin/psi4-config
    - share/psi4/scripts/setenv.py
    - share/psi4/plugin/Makefile.template
    - share/psi4/python/pcm_placeholder.py

requirements:
  build:
    - ambit            # [osx]
    - boost >=1.57     # [osx]
    - cmake >3
    - dftd3            # [linux]  # for test dashboard
    - gcc              # [osx]    # build w/ gcc, gfortran
    - hdf5
    - libgcc           # [linux]
    - numpy                       # for psi4 execution w/i ctest and sphinxman
    - pcmsolver
    - pychemps2
    - python 2.7*
    - sphinx 1.3*      # [linux]  # for docs
    - zlib
  run:
    - ambit            # [osx]    # link libambit
    - hdf5                        # link libhdf5, libhdf5_hl
    - libgcc           # [osx]    # link libgfortran, libquadmath, libstdc++, libgcc_s, libgomp
    - libgcc           # [linux]  # link libgcc_s
    - ncurses                     # for psi4 interactive
    - mkl                         # link libiomp5 (psi4.so)
    - numpy
    - pcmsolver                   # link libpcm
    - pychemps2                   # link libchemps2
    - python 2.7*                 # link libpython2.7
    - zlib                        # link libz

test:
  commands:
    # Verify executable.
    - test -f $PREFIX/bin/psi4
    # Verify python module.
    - test -f $PREFIX/lib/python2.7/site-packages/psi4.so
    #- $PREFIX/bin/psi4 --help  # no good; exits 1 even upon success

about:
  home: http://www.psicode.org
  license: GNU General Public License v2 or later (GPLv2+)
  #license_file: LICENSE
  summary: "open-source quantum chemistry"
  #readme: README.md

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../../psi4mangle/psi4
#build/number: 1
#build/string: abc
