{% set version = "1.1.6" %}

package:
  name: libint
  version: {{ version }}

source:
  git_url: git@github.com:psi4/libint.git              # [linux]
  git_url: https://github.com/psi4/libint.git          # [osx]
  #git_tag: v{{ version }}

build:
  number: 1
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=3.0
    - gcc              # [osx]    # build w/conda gcc
  run:
    - libgcc           # [osx]    # link libstdc++, libgcc_s

test:
  commands:
    # Verify libraries and executable.
    - test -f $PREFIX/lib/libint.so       # [linux]
    - test -f $PREFIX/lib/libderiv.so     # [linux]
    - test -f $PREFIX/lib/libint.dylib    # [osx]
    - test -f $PREFIX/lib/libderiv.dylib  # [osx]

about:
  home: https://github.com/psi4/libint
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "two-body molecular integrals over Gaussian functions library"
  readme: README.md

