{% set version = "1.2.1" %}

package:
    name: libint
    version: {{ version }}

source:
    git_url: git@github.com:evaleev/libint.git           # [linux]
    git_url: https://github.com/evaleev/libint.git       # [osx]
    git_tag: 3f14ff0  # v1, ~1.2.1

build:
    number: 4                                            # [linux]  # 4: AVX-512
    number: 1                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    provides_features:
        ameri: am{{ MAX_AM_ERI }}
    run_exports:
        - {{ pin_subpackage('libint', max_pin='x.x') }}
    ignore_run_exports:
        # gcc symbols linked statically. c++ only a formality to build c lib.
        - libgcc-ng                                      # [linux]
        - libstdcxx-ng                                   # [linux]
        - libcxx                                         # [osx]

requirements:
    build:
        - cmake >=3.0
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libint$SHLIB_EXT
        - test -f $PREFIX/lib/libderiv$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libint.so && return 0  # [linux]
        - ldd -v $PREFIX/lib/libint.so                 # [linux]
        - otool -L $PREFIX/lib/libint.dylib            # [osx]
        - conda-inspect linkages libint --show-files

about:
    home: https://github.com/evaleev/libint/tree/v1
    dev_url: https://github.com/evaleev/libint
    doc_url: http://evaleev.github.io/libint/
    # doc_source_url:
    license: LGPL-3.0+
    license_url: https://opensource.org/licenses/LGPL-3.0+
    license_file: LICENSE
    license_family: LGPL
    summary: "E. Valeev and J. Fermann's two-body Gaussian molecular integrals"
    # description: >
