{% set version = "1.2.1" %}

package:
  name: libint
  version: {{ version }}

source:
  git_url: git@github.com:evaleev/libint.git           # [linux]
  git_url: https://github.com/evaleev/libint.git       # [osx]
  git_tag: 3f14ff0  # v1, ~1.2.1
  #git_tag: release-1-2-1

build:
  number: 0
  binary_relocation: true
  skip: true                                           # [win]
  features:
    - am7

requirements:
  build:
    - cmake >=3.0
    - am7
  run:
    - am7

test:
  commands:
    # Verify library
    - test -f $PREFIX/lib/libint$SHLIB_EXT
    - test -f $PREFIX/lib/libderiv$SHLIB_EXT
    # Inspect linkage
    - ldd -r -u $PREFIX/lib/libint.so && return 0  # [linux]
    - ldd -v $PREFIX/lib/libint.so                 # [linux]
    - otool -L $PREFIX/lib/libint.dylib            # [osx]
    - conda-inspect linkages libint --show-files

about:
  home: https://github.com/evaleev/libint/tree/v1
  dev_url: https://github.com/evaleev/libint
  doc_url: http://evaleev.github.io/libint/
  license: LGPL-3.0+
  license_url: https://opensource.org/licenses/LGPL-3.0+
  license_file: LICENSE
  license_family: LGPL
  summary: E. Valeev and J. Fermann's two-body Gaussian molecular integrals
  #description:
