{% set version = "2.6.0" %}

package:
    name: libint2
    version: {{ version }}

source:
    url: https://github.com/loriab/libint/archive/l2cmake.zip
    #git_url: git@github.com:evaleev/libint.git           # [linux]
    #git_url: https://github.com/evaleev/libint.git       # [osx]
    #git_tag: 5c89451  # L5-6: v1, 1.2.1 + 13 = 5c89451, L5: am8, L6M2: hand-edited to incl libderiv/libderiv.h
    #                  # L3-4,M1: v1, ~1.2.1 = 3f14ff0, am6 L4: AVX-512
    git_tag: l2cmake

build:
    number: 2                                            # [linux]  # 2 turns off sph eri3
    number: 0                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    run_exports:
        - {{ pin_subpackage('libint2', max_pin='x') }}
    #ignore_run_exports:
    #    # gcc symbols linked statically. c++ only a formality to build c lib.
    #    - libgcc-ng                                      # [linux]
    #    - libstdcxx-ng                                   # [linux]
    #    - libcxx                                         # [osx]

requirements:
    build:
        - cmake >=3.8
        - {{ compiler('cxx') }}
        - ninja
    host:
        - boost
        - eigen
        - mpfr

test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libint2$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libint2.so && return 0 # [linux]
        - ldd -v $PREFIX/lib/libint2.so                # [linux]
        - otool -L $PREFIX/lib/libint.dylib            # [osx]
        - conda-inspect linkages libint2 --show-files

about:
    home: https://github.com/evaleev/libint
    dev_url: https://github.com/evaleev/libint
    doc_url: http://evaleev.github.io/libint/
    # doc_source_url:
    license: LGPL-3.0+
    license_url: https://opensource.org/licenses/LGPL-3.0+
    license_file: LICENSE
    license_family: LGPL
    summary: "E. Valeev and J. Fermann's two-body Gaussian molecular integrals"
    # description: >


# NOTES
# -----

# * tried to build an AM6 for linux build/number: 2 at libint2_1574565922374 but it stopped compiling. could be fixable
