{% set version = "1.8.4" %}

package:
  name: pychemps2
  version: {{ version }}

source:
  git_url: git@github.com:SebWouters/CheMPS2.git       # [linux]
  git_url: https://github.com/SebWouters/CheMPS2.git   # [osx]
  git_tag: v{{ version }}

build:
  number: 0                                            # [linux]
  number: 9  # 55d6 incr 8-->9 but unbuild             # [osx]
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - gcc-5-mp         # [linux]  # needed since chemps2 not incl in rt
    - chemps2 {{ version }}
    - cython
    - numpy
    - python x.x
  run:
    - chemps2 {{ version }}       # link libchemps2
    - numpy
    - python x.x

test:
  commands:
    # Verify python module
    - test -f ${SP_DIR}/PyCheMPS2.so                               # [py27]
    - test -f ${SP_DIR}/PyCheMPS2.cpython-35m-x86_64-linux-gnu.so  # [py35 and linux]
    - test -f ${SP_DIR}/PyCheMPS2.cpython-35m-darwin.so            # [py35 and osx]
    - test -f ${SP_DIR}/PyCheMPS2.cpython-36m-x86_64-linux-gnu.so  # [py36 and linux]
    - test -f ${SP_DIR}/PyCheMPS2.cpython-36m-darwin.so            # [py36 and osx]

about:
  home: http://sebwouters.github.io/CheMPS2
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "python interface to S. Wouters' spin-adapted implementation of DMRG for ab initio quantum chemistry"
  readme: README.md

