{% set version = "1.8.3" %}

package:
  name: pychemps2
  version: {{ version }}

source:
  git_url: https://github.com/loriab/CheMPS2.git       # [linux]
  git_tag: config6
  #git_url: git@github.com:SebWouters/CheMPS2.git       # [linux]
  #git_url: https://github.com/SebWouters/CheMPS2.git   # [osx]
  #git_tag: v{{ version }}

build:
  number: 7
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - chemps2 {{ version }}
    - cython
    - numpy
    - python x.x
  run:
    - chemps2 {{ version }}       # link libchemps2
    - numpy
    - python x.x

test:
  commands:
    # Verify python module.
    - test -f ${PREFIX}/lib/python2.7/site-packages/PyCheMPS2.so  # [py27]
    - test -f ${PREFIX}/lib/python3.5/site-packages/PyCheMPS2.cpython-35m-x86_64-linux-gnu.so  # [py35 and linux]
    - test -f ${PREFIX}/lib/python3.5/site-packages/PyCheMPS2.cpython-35m-darwin.so  # [py35 and osx]

about:
  home: http://sebwouters.github.io/CheMPS2
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "python interface to S. Wouters' spin-adapted implementation of DMRG for ab initio quantum chemistry"
  readme: README.md

