{% set version = "3.0.6" %}

{% set defisa = "avx2" %}
{% set isa = environ.get("PSI_BUILD_ISA", defisa) %}

package:
  name: erd
  version: {{ version }}

source:
  git_url: git@github.com:psi4/erd.git                 # [linux]
  git_url: https://github.com/psi4/erd.git             # [osx]
  git_tag: v{{ version }}

build:
  number: 1                                            # [linux]
  number: 3                                            # [osx]
  binary_relocation: true
  skip: true                                           # [win]
  script_env:
    - PSI_BUILD_ISA                                    # [osx]
  {% if isa != defisa %}
  features:
    - {{ isa }}                                        # [osx]
  {% endif %}

requirements:
  build:
    - cmake >=3.0
    - gcc              # [osx]    # build w/conda gfortran
    - gcc-5-mp         # [linux]  # detect Fortran/C module mangling
    {% if isa != defisa %}
    - {{ isa }}        # [osx]    # for oldmac selection
    {% endif %}
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath, libgcc_s
    {% if isa != defisa %}
    - {{ isa }}        # [osx]    # track oldmac
    {% endif %}

test:
  commands:
    # Verify library
    - test -f $PREFIX/lib/liberd$SHLIB_EXT
    # Inspect linkage
    - ldd -r -u $PREFIX/lib/liberd.so && return 0      # [linux]
    - ldd -v $PREFIX/lib/liberd.so                     # [linux]
    - otool -L $PREFIX/lib/liberd.dylib                # [osx]
    - conda-inspect linkages erd --show-files

about:
  home: https://github.com/psi4/erd
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "AcesIII electron repulsion integrals"
  readme: README.md

