{% set version = "1.8.3" %}

{% set mklver = "2017.0.3" %}
{% set defisa = "avx2" %}
{% set isa = environ.get("PSI_BUILD_ISA", defisa) %}


package:
  name: chemps2
  version: {{ version }}

source:
  #git_url: https://github.com/loriab/CheMPS2.git       # [linux]
  #git_url: https://github.com/loriab/CheMPS2.git   # [osx]
  #git_tag: config6
  git_url: git@github.com:SebWouters/CheMPS2.git       # [linux]
  git_url: https://github.com/SebWouters/CheMPS2.git   # [osx]
  git_tag: 55d6b38  # v1.8.3-12
  #git_tag: v{{ version }}

build:
  number: 5                                            # [linux]  # 55d6 incr 4-->5 but unbuild
  number: 6                                            # [osx]
  binary_relocation: true
  skip: true                                           # [win]
  script_env:
    - PSI_BUILD_ISA                                    # [osx]
  {% if isa != defisa %}
  features:
    - {{ isa }}                                        # [osx]
  {% endif %}

requirements:
  build:
    - cmake >=3.0
    - hdf5 1.8.17                 # PIN-TO-BUILD
    - gcc-5-mp         # [linux]
    - zlib
    - mkl {{ mklver }} # [osx]
    {% if isa != defisa %}
    - {{ isa }}        # [osx]    # for oldmac selection
    {% endif %}
  run:
#    - gcc-5-mp         # [linux]  # link libgcc_s  # trying not incl@rt on same grounds as libefp
    - hdf5 1.8.17                  # link libhdf5, libhdf5_hl  PIN-TO-BUILD
    - mkl              # [linux]  # link libiomp5
    - zlib             #          # link libz
    - mkl {{ mklver }} # [osx]
    {% if isa != defisa %}
    - {{ isa }}        # [osx]    # track oldmac
    {% endif %}

##    - libgcc           # [osx]    # link libstdc++, libgcc_s, libgomp
##    - libgcc           # [linux]  # link libgcc_s
###    - gcc5             # [linux]  # link libgcc_s PIN-TO-BUILD
#    - gcc-5           # [linux]  # link libgcc_s
##    - mkl              # [linux]  # link iomp5
##    - zlib                        # link libz

test:
  commands:
    # Verify libraries and executable.
    - test -f $PREFIX/lib/libchemps2$SHLIB_EXT
    - test -f $PREFIX/bin/chemps2
    # Inspect linkage
    - ldd -r -u $PREFIX/lib/libchemps2.so && return 0  # [linux]
    - ldd -v $PREFIX/lib/libchemps2.so                 # [linux]
    - otool -L $PREFIX/lib/libchemps2.dylib            # [osx]
    - conda-inspect linkages chemps2 --show-files

about:
  home: http://sebwouters.github.io/CheMPS2
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "a spin-adapted implementation of DMRG for ab initio quantum chemistry"
  readme: README.md

