{% set version = "1.8" %}

package:
  name: chemps2
  version: {{ version }}

source:
  git_url: git@github.com:loriab/CheMPS2.git       # [linux]
  git_url: https://github.com/loriab/CheMPS2.git   # [osx]
  git_tag: configpy2
  #git_url: git@github.com:SebWouters/CheMPS2.git       # [linux]
  #git_url: https://github.com/SebWouters/CheMPS2.git   # [osx]
  #git_tag: v{{ version }}

build:
  number: 2
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - cmake >=2.8.11
    - gcc              # [osx]    # build w/conda gcc
    - hdf5
    - libgcc           # [linux]
#    - gcc-5            # [linux]
    - mkl              # [linux]
    - zlib
  run:
    - hdf5 1.8.17                 # PIN-TO-BUILD
    - libgcc           # [osx]    # link libstdc++, libgcc_s, libgomp
    - libgcc           # [linux]  # link libgcc_s
#    - gcc5             # [linux]  # link libgcc_s PIN-TO-BUILD
    - mkl              # [linux]  # link iomp5
    - zlib                        # link libz

test:
  commands:
    # Verify libraries and executable.
    - test -f $PREFIX/lib/libchemps2.so     # [linux]
    - test -f $PREFIX/lib/libchemps2.dylib  # [osx]
    - test -f $PREFIX/bin/chemps2

about:
  home: http://sebwouters.github.io/CheMPS2
  license: GNU General Public License v2 or later (GPLv2+)
  summary: "a spin-adapted implementation of DMRG for ab initio quantum chemistry"
  readme: README.md

