{% set version = "3.1.1" %}

package:
  name: dftd3
  version: {{ version }}

source:
  fn: dftd3.tgz
  url: http://www.thch.uni-bonn.de/tc/downloads/DFT-D3/data/dftd3.tgz

build:
  number: 2
  binary_relocation: false   # [linux]

requirements:
  build:
    - gcc              # [osx]  # build w/conda gfortran
  run:
    - libgcc           # [osx]  # link against lgfortran, lquadmath, lgcc_s

test:
  commands:
    # Verify executable.
    - test -f $PREFIX/bin/dftd3

about:
  home: "http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=DFT-D3&lang=english"
  license: "custom"
  summary: "S. Grimme's dispersion correction for DFT, Hartree–Fock, and semi-empirical quantum chemical methods"

# Anaconda.org description
#**Site:** <a href="http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=DFT-D3&lang=english">http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=DFT-D3&lang=english</a><br>**License:** <a href="http://www.thch.uni-bonn.de/tc/index.php?section=impressum&lang=english">http://www.thch.uni-bonn.de/tc/index.php?section=impressum&lang=english</a>

# to conda build package from local source rather than github, substitute like below
#package/version: 0.1.6
#source/path: ../../psi4mangle/psi4
#build/number: 1
#build/string: abc

