{% set version = "3.2.0" %}

package:
    name: dftd3
    version: {{ version }}

source:
    fn: dftd3.tgz
    url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/dftd3.tgz

build:
    number: 8                                            # [linux]
    number: 7                                            # [osx]
    binary_relocation: true
    skip: true                                           # [win]
    ignore_run_exports:
        # unused libraries
        - libgcc-ng
        - libgfortran-ng

requirements:
    build:
        - {{ compiler('fortran') }}

test:
    commands:
        # Verify executable
        - test -f $PREFIX/bin/dftd3
        # Inspect linkage
        - otool -L $PREFIX/bin/dftd3                     # [osx]
        - conda-inspect linkages dftd3 --show-files

about:
    home: http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=DFT-D3&lang=english
    # dev_url:
    doc_url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/man.pdf
    # doc_source_url:
    license: GPL-1.0+
    # license_url:
    # license_file:
    license_family: GPL
    summary: "S. Grimme's dispersion correction for DFT, Hartree--Fock, and semi-empirical quantum chemical methods"
    # description: >
